### ISSUE TITLE
Commented out lines are not ignored

### ISSUE THREAD

**Issue by mtakaki** [tkrille/dropwizard-template-config#13] opened 2016-04-16 07:46 UTC
Lines that are commented out are not ignored by the template engine.

I have some configurations that reads values from the environment variable, but I commented out those lines and the template engine still tried to replace them.

To reproduce it, just add something like this in the file:

```yaml
#token: ${env.TEST}
```

**Comment by tkrille** [comment] 2016-04-16 13:31
Hello @mtakaki,

this is an issue caused by the underlying template engine, Freemarker. It doesn't know anything at all about YAML and so cannot ignore commented out lines. You should try to use Freemarker comments:

```
<#-- token: ${env.TEST} -->.
```

**Comment by mtakaki** [comment] 2016-04-16 14:31
Awesome! It works using Freemarker comments! :)
I guess you can just close it as not an issue.

Thanks for your help!

**Comment by tkrille** [comment] 2016-04-16 16:37
Happy to help. I will add the answer given to the documentation and then close the issue.

**Closed** 2016-04-16 16:58 UTC
